services:
  _defaults:
    autowire: true
    autoconfigure: true

  ModuleA\SubmoduleA\Controller\:
    resource: '../../../src/ModuleA/SubmoduleA/Controller/'
    tags: [ 'controller.service_arguments' ]
